### ISSUE TITLE
Add `trim` operation in `to`

### ISSUE THREAD

**Issue by nobe4** [nobe4/action-ln#209]
E.g. 
```yaml
links:
  - from: go/.ln-config.yaml
    to: .ln-config.yaml

  - from: go/script/lint
    to: script/lint

  - from: go/script/test
    to: script/test
```

could be

```yaml
links:
  - from: 
      - go/.ln-config.yaml
      - go/script/lint
      - go/script/test
    to:
      trim_prefix: `go/`
```
