### ISSUE TITLE
Allow for other files format

### ISSUE THREAD

**Issue by nobe4** [nobe4/action-ln#33]
> [!NOTE]
> The following examples include a `ref` parameter, that's not yet implemented but will be done in #34. Parsing should allow for it even if it stays unused for now.

Currently, the parsing of files location is restricted to:

```yaml
file:
  repo: owner/repo
  path: path/to/file
  ref: ref
```

See [implementation](https://github.com/nobe4/action-ln/blob/main/src/file.js#L31-L80).

Which is very descriptive, but can be too verbose at time.

It should be possible to have different ways to configure the file portion of the configuration, in one line.

Proposed additional formats:

0. GitHub full URL:

    ```yaml
    file: https://github.com/owner/repo/blob/ref/path/to/file
    ```

1. Even more verbose:

    ```yaml
    file:
      owner: owner
      repo: repo
      path: path/to/file
      ref: ref
    ```

2. Shortened URL:

    ```yaml
    file: owner/repo/blob/ref/path/to/file
    ```

3. Alternative URL:
  
    ```yaml
    file: owner/repo/path/to/file@ref
    ```

This could simplify the config.

Whether it's a good idea to implement all those is left up for discussion.
I think at least 0. and 1. should be done.

The implementation should work in the following way:

- Given an ordered list of parsing methods
- Each should be applied one after the other
- If the parsed info has all the fields setup: stop parsing
- If no parsing yielded a correct setup: fail
