### ISSUE TITLE
Support simpler defaults

### ISSUE THREAD

**Issue by nobe4** [nobe4/action-ln#43]
E.g.

```yaml
- from:
    repo: x/y
    path: z
  to:
    path: z
```

could be simplified by just 

```yaml
- from:
    repo: x/y
    path: z
```

no repo => current repo
no path => from path
