### ISSUE TITLE
Feature: Add a global settings block to the config

### ISSUE THREAD

**Issue by GrantBirki** [nobe4/action-ln#81]
It would be cool if there was a global config block to set some defaults for all the link blocks. Maybe something like this?

```yaml
defaults:
  ref: main
  labels:
    - ln
    - dependencies

links:
  - from:
      repo: grantbirki/ruby-template
      path: script/bootstrap
      ref: main # should use the defaults unless this is explicitly set
    to:
      repo: grantbirki/ldap-api
      path: script/bootstrap
```

The `labels` attribute is a new feature (in my example) but something I thought of while writing this issue as well. With things like dependabot you can add `labels` to the PRs it opens to sort on which is quite nice.
