### ISSUE TITLE
Feature: Support an array of `to` values

### ISSUE THREAD

**Issue by GrantBirki** [nobe4/action-ln#82]
It would be really cool if I could "federate" a single file (using `from`), with multiple `to` values.

For example, something like this:

```yaml
links:
  - from:
      repo: nobe4/repo-1
      path: README.md
    to:
      - repo: nobe4/repo-2
        path: README.md
      - repo: nobe4/repo-3
        path: README.md
      - repo: nobe4/repo-4
        path: README.md
```

**Comment by nobe4** [comment]
Yes ✨ That was one of my idea, but I didn't write it up.

Actually, I wanted the `from` also to be a list, to federate easier:

```
links:
  - from:
      repo: nobe4/repo-1
      path: README.md
    to:
      - repo: nobe4/repo-2
        path: README.md
      - repo: nobe4/repo-3
        path: README.md
  - from:
    - repo: nobe4/repo-4
      path: a-file
    - repo: nobe4/repo-5
      path: another-file
    to:
      - repo: nobe4/repo-6
      - repo: nobe4/repo-7

# nobe4/repo-1:README.md => nobe4/repo-2:README.md
# nobe4/repo-1:README.md => nobe4/repo-3:README.md
# nobe4/repo-4:a-file => nobe4/repo-6:a-file
# nobe4/repo-4:a-file => nobe4/repo-7:a-file
# nobe4/repo-5:another-file => nobe4/repo-6:another-file
# nobe4/repo-5:another-file => nobe4/repo-7:another-file
```

This will surely happen eventually. I think it should even happen before #68
